# Generated by Django 3.0 on 2021-12-14 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0002_auto_20211214_1029'),
    ]

    operations = [
    	migrations.SeparateDatabaseAndState(
    		database_operations=[
    			migrations.AlterModelTable('Profile', 'profiles_profile'),
    		],
    		state_operations=[
		        migrations.DeleteModel(
		            name='Profile',
		        ),
    		],
    	),
    ]